### ISSUE TITLE
range of saturation and lightness in HSL should be 0.0-1.0

### ISSUE THREAD

**Issue by lebensterben** [ChevyRay/color_space#1]
In HSL, hue is within 0-360 degree, while saturation and lightness are between 0.0 % to 100.0 %.
Since formally the range of the latter two is [0, 1], I propose to revise the current implementation, so that saturation and lightness are not multiplied by 100.

**Comment by ChevyRay** [comment]
i'd prefer it that way as well, the 0-100 range that a lot of HSL apis use (even when back-to-back with 0-1 range HSV) was confusing, but it was so common that i did it here as well.

i think 0-1 would be better and just leave the *100 operations to the end user if they want it in that space, since it's a trivial conversion anyhow and i prefer the api being more consistent

**Comment by ChevyRay** [comment]
fixed in [fa88f87](https://github.com/ChevyRay/color_space/commit/fa88f87aad12312f2f259c4b548af8bf06cb0d13)
